name: Generate docs

on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'bibliography/**'
      - 'papers/**'
      - 'thesis/**'
      - 'slides/**'
      - 'project/**'
      - 'Makefile'
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Install aspell with Spanish dictionary
        run: |
          sudo apt-get update
          sudo apt-get install -y aspell aspell-es

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::ggplot2
            any::ggthemes
            any::rmarkdown
            any::knitr

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Marp
        run: npm install -g @marp-team/marp-cli

      - name: Generate PDFs
        run: make all

      - name: Archive PDFs
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: output/**/*.pdf

      - name: Build metadata
        id: meta
        run: echo "timestamp=$(date -u +'%Y-%m-%d %H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Update pre-release with PDFs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'output/**/*.pdf'
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: pre-release
          name: "Pre-release docs - ${{ steps.meta.outputs.timestamp }}"
          body: "Automated documentation build executed at ${{ steps.meta.outputs.timestamp }} (UTC)."
          allowUpdates: true
          removeArtifacts: true

      - name: Attach PDFs to official release
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'output/**/*.pdf'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          allowUpdates: true
          removeArtifacts: true
