name: Build Papers

on:
  push:
    paths:
      - 'papers/**'
      - '.github/workflows/papers.yml'
  pull_request:
    paths:
      - 'papers/**'
  release:
    types: [created, edited]
  workflow_dispatch:

jobs:
  papers:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::ggplot2
            any::ggthemes
            any::rmarkdown
            any::knitr

      - uses: actions/cache@v4
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - name: Set up Tectonic
        uses: wtfjoke/setup-tectonic@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update bibliography
        run: make bibliography

      - name: Build Papers
        run: make papers

      - uses: actions/upload-artifact@v4
        with:
          name: papers
          path: output/papers/*.pdf

      - name: Build metadata
        id: meta
        run: echo "timestamp=$(date -u +'%Y-%m-%d %H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Update pre-release with PDFs
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'pull_request')
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            output/**/*.pdf
            output/**/*.docx
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag: pre-release
          name: "Pre-release docs - ${{ steps.meta.outputs.timestamp }}"
          body: "Automated documentation build executed at ${{ steps.meta.outputs.timestamp }} (UTC)."
          allowUpdates: true
          removeArtifacts: false

      - name: Attach PDFs to official release
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'output/**/*.pdf'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          allowUpdates: true
          removeArtifacts: false
